### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by gen-failure** [thedracle/cordova-android-chromeview#1]
Hi,

I tried to follow instructions in README file and this is error I found after I called the bin/create script

BUILD FAILED
/Applications/Android SDK/sdk/tools/ant/build.xml:712: The following error occurred while executing this line:
/Applications/Android SDK/sdk/tools/ant/build.xml:726: Compile failed; see the compiler error output for details.

Total time: 3 seconds
An unexpected error occurred: ant jar > /dev/null exited with 1
Deleting project...

This are the problematic lines...

 710     
 711     <target name="-compile" depends="-pre-build, -build-setup, -code-gen, -pre-compile">
 712         <do-only-if-manifest-hasCode elseText="hasCode = false. Skipping...">
 713             
 714             <path id="project.javac.classpath">
 715                 <path refid="project.all.jars.path" />
 716                 <path refid="tested.project.classpath" />
 717                 <path path="${java.compiler.classpath}" />
 718             </path>
 719             <javac encoding="${java.encoding}"
 720                     source="${java.source}" target="${java.target}"
 721                     debug="true" extdirs="" includeantruntime="false"
 722                     destdir="${out.classes.absolute.dir}"
 723                     bootclasspathref="project.target.class.path"
 724                     verbose="${verbose}"
 725                     classpathref="project.javac.classpath"
 726                     fork="${need.javac.fork}">
 727                 <src path="${source.absolute.dir}" />
 728                 <src path="${gen.absolute.dir}" />
 729                 <compilerarg line="${java.compilerargs}" />
 730             </javac>

**Comment by gen-failure** [comment]
I am sorry, I supposed that chromeview is already included

**Comment by Spittal** [comment]
Hey Darken,

I'm having the same issues, could you explain how you solved them?

**Comment by albi90** [comment]
@DarkenCZ im having this issue to can you explain how you fixed it?

**Comment by gen-failure** [comment]
ATM I am not remember exact walkthrough, but the point is, that chromeview it's not included in the wrapper. I had to compile it separately and the move to wrapper libraries.

**Comment by albi90** [comment]
Thanks @DarkenCZ you helped me solve it!
